insert into item (name) values
('Painel 1'),
('Painel 2'),
('Painel 3'),
('Painel 4'),
('Painel 5'),
('Painel 6'),
('Painel 7'),
('Painel 8'),
('Outdoor 1'),
('Outdoor 2'),
('Outdoor 3'),
('Outdoor 4'),
('Outdoor 5'),
('Outdoor 6'),
('Outdoor 7'),
('Outdoor 8'),
('Marketing Digital'),
('Site'),
('Arte Gráfica'),
('Outros');
